from .main import dotenv_values as dotenv_values, find_dotenv as find_dotenv, get_key as get_key, load_dotenv as load_dotenv, set_key as set_key, unset_key as unset_key
from typing import Any, Optional

def load_ipython_extension(ipython: Any) -> None: ...
def get_cli_string(path: Optional[str]=..., action: Optional[str]=..., key: Optional[str]=..., value: Optional[str]=..., quote: Optional[str]=...) -> str: ...
